language: php

php:
  - 7.2

sudo: true

git:
  depth: 1

install:
  - travis_retry composer update --no-interaction --no-progress

script:
  - vendor/bin/codecept run unit --coverage --coverage-text
  - find src/ -type f -print0 | xargs -0 -n1 php -l
  - vendor/bin/phpcs src/ --standard=psr2

notifications:
  email:
    - antonamru@gmail.com
